# Generated by Django 6.0.3 on 2026-04-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
    ]
